opensandbox-controller:
  namespaceOverride: opensandbox-system
  controller:
    image:
      repository: opensandbox/controller
      tag: v0.2.0

opensandbox-server:
  namespaceOverride: opensandbox-system
  server:
    replicaCount: 1
    image:
      repository: opensandbox/server
      tag: v0.2.2
    env:
      - name: OPENSANDBOX_SERVER_API_KEY
        valueFrom:
          secretKeyRef:
            name: opensandbox-api-key
            key: api-key
  configToml: |
    [server]
    host = "0.0.0.0"
    port = 80
    max_sandbox_timeout_seconds = 86400

    [log]
    level = "INFO"

    [runtime]
    type = "kubernetes"
    execd_image = "opensandbox/execd:v1.0.21"

    [storage]
    allowed_host_paths = []
    volume_default_size = "10Gi"

    [kubernetes]
    kubeconfig_path = ""
    namespace = "efferva-sandboxes"
    informer_enabled = true
    workload_provider = "batchsandbox"
    image_pull_policy = "IfNotPresent"
    batchsandbox_template_file = "/etc/opensandbox/example.batchsandbox-template.yaml"

    [egress]
    image = "opensandbox/egress:v1.1.5"
    mode = "dns+nft"
